export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h1>
            Navbar
            <ul>
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="/inicio">Login</a>
              </li>
              <li>
                <a href="registro">Registro</a>
              </li>
            </ul>
          </h1>
        </nav>
        {children}
      </body>

    </html>
  )
}
